name: SSH to Azure VM and Deploy API

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the 'main' branch

jobs:
  ssh-to-azure-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "your-private-key" > ~/.ssh/hr.pem
          chmod 600 ~/.ssh/hr.pem

      - name: Add Azure VM to known hosts
        run: |
          ssh-keyscan -t rsa -H 20.55.1.67 >> ~/.ssh/known_hosts || true

      - name: Debug - List files in the current directory
        run: ls -R

      - name: List files in the backend directory
        run: ls -R ./simple-backend-api/

      # Your other deployment steps follow...
