name: SSH to Azure VM and Deploy API

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the 'main' branch

jobs:
  ssh-to-azure-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }} # Ensure hr.pem is saved in Secrets as SSH_KEY
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/hr.pem
          chmod 600 ~/.ssh/hr.pem

      - name: Add Azure VM to known hosts
        run: |
          ssh-keyscan -t rsa -H 20.55.1.67 >> ~/.ssh/known_hosts || true

      - name: List files in the source directory
        run: |
          ls -R ./

      - name: Copy project files to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 20.55.1.67 # Azure VM IP address
          username: azureuser # Azure VM username
          key: ~/.ssh/hr.pem # Path to SSH key
          source: "./" # Source directory in your GitHub repo
          target: "/home/azureuser/simple-backend-api/" # Target directory on Azure VM
