name: Deploy Application

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  workflow_dispatch:  # Allow manual trigger via the GitHub Actions interface

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Set up SSH key
        run: |
          # Create the .ssh directory if it doesn't exist
          mkdir -p ~/.ssh
          
          # Output the private key to verify it's correctly passed
          echo "$SSH_PRIVATE_KEY"  # This is for debugging; remove after verification
          
          # Write the SSH private key to the id_rsa file
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          
          # Set proper permissions for the private key
          chmod 600 ~/.ssh/id_rsa
          
          # Add the VM host to the known_hosts file to avoid SSH warnings
          ssh-keyscan -H $VM_HOST >> ~/.ssh/known_hosts
          
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VM_HOST: ${{ secrets.VM_HOST }}

      - name: Deploy application
        run: |
          # Enable verbose mode for debugging SSH connection
          ssh -v -o StrictHostKeyChecking=no $VM_USER@$VM_HOST 'sudo pkill -f "node index.js" || true'
          # Add other deployment commands here
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_HOST: ${{ secrets.VM_HOST }}
