- name: Copy project files to Azure VM
  uses: appleboy/scp-action@master
  with:
    host: 20.55.1.67
    username: azureuser
    key: hr.pem
    source: "./simple-backend-api/*"
    target: "/home/azureuser/simple-backend-api/"
