name: SSH to Azure VM and Deploy API

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the 'main' branch

jobs:
  ssh-to-azure-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        cp hr.pem ~/.ssh/
        chmod 600 hr.pem

    - name: Add Azure VM to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 20.55.1.67 >> ~/.ssh/known_hosts

    - name: SSH into Azure VM and Deploy API
      run: |
        ssh -o StrictHostKeyChecking=no -i hr.pem azureuser@20.55.1.67 << 'EOF'
          # Update the VM
          sudo apt update
          sudo apt upgrade -y
          
          # Install Node.js (with npm)
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt install -y nodejs

          # Install Nginx (if you plan to use it)
          sudo apt install -y nginx

          # Navigate to the backend directory (adjust this path to your app's location)
          cd /

          # Install dependencies using npm
          npm install

          # Start the API (assuming it's a Node.js app)
          nohup node index.js &

          # Allow HTTP traffic through the firewall
          sudo ufw allow 80/tcp
          
          # Restart Nginx to ensure it's working as expected
          sudo systemctl restart nginx
        EOF

    - name: Test the API is running
      run: |
        curl http://20.55.1.67/sayHello
