name: SSH to Azure VM

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the 'main' branch

jobs:
  ssh-to-azure-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        # Ensure the SSH directory exists
        mkdir -p ~/.ssh
        
        # Copy the hr.pem file from the repository to the SSH folder
        cp ./ssh/hr.pem ~/.ssh/

        # Set the correct permissions for the private key
        chmod 600 hr.pem

    - name: Add Azure VM to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 20.55.1.67 >> ~/.ssh/known_hosts

    - name: SSH into Azure VM
      run: |
        # Connect to the Azure VM using the hr.pem private key
        ssh -o StrictHostKeyChecking=no -i hr.pem azureuser@20.55.1.67 << 'EOF'
          # Add any commands you want to run on the VM here
          echo "Connected successfully!"
          sudo apt update
          sudo apt upgrade -y
        EOF
